<i>Copyright (c) Recommenders contributors.</i>

<i>Licensed under the MIT License.</i>

# Vowpal Wabbit Deep Dive

<center>
<img src="https://github.com/VowpalWabbit/vowpal_wabbit/blob/master/logo_assets/vowpal-wabbits-github-logo.png?raw=true" height="30%" width="30%" alt="Vowpal Wabbit">
</center>

[Vowpal Wabbit](https://github.com/VowpalWabbit/vowpal_wabbit) is a fast online machine learning library that implements several algorithms relevant to the recommendation use case.

The main advantage of Vowpal Wabbit (VW) is that training is done in an online fashion typically using Stochastic Gradient Descent or similar variants, which allows it to scale well to very large datasets. Additionally, it is optimized to run very quickly and can support distributed training scenarios for extremely large datasets. 

VW is best applied to problems where the dataset is too large to fit into memory but can be stored on disk in a single node. Though distributed training is possible with additional setup and configuration of the nodes. The kinds of problems that VW handles well mostly fall into the supervised classification domain of machine learning (Linear Regression, Logistic Regression, Multiclass Classification, Support Vector Machines, Simple Neural Nets). It also supports Matrix Factorization approaches and Latent Dirichlet Allocation, as well as a few other algorithms (see the [wiki](https://github.com/VowpalWabbit/vowpal_wabbit/wiki) for more information).

A good example of a typical deployment use case is a Real Time Bidding scenario, where an auction to place an ad for a user is being decided in a matter of milliseconds. Feature information about the user and items must be extracted and passed into a model to predict likelihood of click (or other interaction) in short order. And if the user and context features are constantly changing (e.g. user browser and local time of day) it may be infeasible to score every possible input combination before hand. This is where VW provides value, as a platform to explore various algorithms offline to train a highly accurate model on a large set of historical data then deploy the model into production so it can generate rapid predictions in real time. Of course this isn't the only manner VW can be deployed, it is also possible to use it entirely online where the model is constantly updating, or use active learning approaches, or work completely offline in a pre-scoring mode.

<h3>Vowpal Wabbit for Recommendations</h3>

In this notebook we demonstrate how to use the VW library to generate recommendations on the [MovieLens](https://grouplens.org/datasets/movielens/) dataset.

Several things are worth noting in how VW is being used in this notebook:

VW is used here through the `VW` class in `recommenders.models.vowpal_wabbit.vw`, a thin wrapper around the python bindings installed with the `vowpalwabbit` pip package, so no separate installation of the vw binary is needed. The class follows the same `fit()`, `predict()` and `recommend_k_items()` interface as the other models in this repository, and its parameters are the vw [command line options](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments) passed as keyword arguments, so `VW(q="ui", b=26)` is the same as `vw -q ui -b 26`.

VW expects a specific [input format](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Input-format); the `VW` class converts the dataframes into that format and passes them to VW for training and scoring.

The examples shown are to demonstrate functional capabilities of VW not to indicate performance advantages of different approaches. There are several hyper-parameters (e.g. learning rate and regularization terms) that can greatly impact performance of VW models which can be adjusted using [command line options](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments). To properly compare approaches it is helpful to learn about and tune these parameters on the relevant dataset.

# 0. Global Setup

In [1]:
import sys
import pandas as pd

from recommenders.datasets.movielens import load_pandas_df
from recommenders.datasets.python_splitters import python_random_split
from recommenders.evaluation.python_evaluation import (
    rmse,
    mae,
    exp_var,
    rsquared,
    map_at_k,
    ndcg_at_k,
    precision_at_k,
    recall_at_k,
)
from recommenders.models.vowpal_wabbit.vw import VW
from recommenders.utils.notebook_utils import store_metadata
from recommenders.utils.timer import Timer

print("System version: {}".format(sys.version))
print("Pandas version: {}".format(pd.__version__))

System version: 3.11.14 (main, Jan 14 2026, 19:35:32) [Clang 21.1.4 ]
Pandas version: 2.3.3

In [2]:
def evaluate(test, predictions, train_time, test_time, logistic=False):
    """Compute the rating metrics and timing of a model
    Args:
        test (pd.DataFrame): test data
        predictions (pd.DataFrame): test data with the prediction column added
        train_time (float): training time in seconds
        test_time (float): prediction time in seconds
        logistic (bool): flag to convert the ratings to a binary label
    Returns:
        (dict): metrics and timing information
    """
    pred_df = predictions.drop(columns="rating")
    test_df = test.copy()

    if logistic:
        # make the true label binary so that the metrics are captured correctly
        test_df["rating"] = test_df["rating"].apply(lambda x: 1 if x >= 3 else -1)
    else:
        # ensure results are integers in correct range
        pred_df["prediction"] = pred_df["prediction"].apply(lambda x: int(max(1, min(5, round(x)))))

    return {
        "RMSE": rmse(test_df, pred_df),
        "MAE": mae(test_df, pred_df),
        "R2": rsquared(test_df, pred_df),
        "Explained Variance": exp_var(test_df, pred_df),
        "Train Time (ms)": train_time * 1000,
        "Test Time (ms)": test_time * 1000,
    }

# 1. Load & Transform Data

In [3]:
# Select MovieLens data size: 100k, 1m, 10m, or 20m
MOVIELENS_DATA_SIZE = '100k'
TOP_K = 10

In [4]:
# load movielens data
df = load_pandas_df(MOVIELENS_DATA_SIZE)

# split data to train and test sets, default values take 75% of each users ratings as train, and 25% as test
train, test = python_random_split(df, 0.75)

# 2. Regression Based Recommendations

When considering different approaches for solving a problem with machine learning it is helpful to generate a baseline approach to understand how more complex solutions perform across dimensions of performance, time, and resource (memory or cpu) usage.

Regression based approaches are some of the simplest and fastest baselines to consider for many ML problems.

## 2.1 Linear Regression

As the data provides a numerical rating between 1-5, fitting those values with a linear regression model is easy approach. This model is trained on examples of ratings as the target variable and corresponding user ids and movie ids as independent features.

By passing each user-item rating in as an example the model will begin to learn weights based on average ratings for each user as well as average ratings per item.

This however can generate predicted ratings which are no longer integers, so some additional adjustments should be made at prediction time to convert them back to the integer scale of 1 through 5 if necessary. Here, this is done in the evaluate function.

In [5]:
"""
Quick description of the parameters used, these are the vw command line options passed as keyword arguments
  Other optional parameters can be found here: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments
  VW uses linear regression by default, so no extra options are needed
  quiet: runs vw in quiet mode silencing the progress output, this is the default
"""
model = VW(col_user="userID", col_item="itemID", col_rating="rating")

with Timer() as train_time:
    model.fit(train)

with Timer() as test_time:
    predictions = model.predict(test)

result = evaluate(test, predictions, train_time.interval, test_time.interval)

comparison = pd.DataFrame(result, index=['Linear Regression'])
comparison

,RMSE,MAE,R2,Explained Variance,Train Time (ms),Test Time (ms)
Linear Regression,0.988453,0.70992,0.227245,0.227255,225.956585,326.466013

## 2.2 Linear Regression with Interaction Features

Previously we treated the user features and item features independently, but taking into account interactions between features can provide a mechanism to learn more fine grained preferences of the users.

To generate interaction features use the quadratic command line argument and specify the namespaces that should be combined: '-q ui' combines the user and item namespaces based on the first letter of each.

Currently the userIDs and itemIDs used are integers which means the feature ID is used directly, for instance when user ID 123 rates movie 456, the training example puts a 1 in the values for features 123 and 456. However when interaction is specified (or if a feature is a string) the resulting interaction feature is hashed into the available feature space. Feature hashing is a way to take a very sparse high dimensional feature space and reduce it into a lower dimensional space. This allows for reduced memory while retaining fast computation of feature and model weights.

The caveat with feature hashing, is that it can lead to hash collisions, where separate features are mapped to the same location. In this case it can be beneficial to increase the size of the space to support interactions between features of high cardinality. The available feature space is dictated by the --bit_precision (-b) <N> argument. Where the total available space for all features in the model is 2<sup>N</sup>. 

See [Feature Hashing and Extraction](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Feature-Hashing-and-Extraction) for more details.

In [6]:
"""
Quick description of the parameters used, these are the vw command line options passed as keyword arguments
  Other optional parameters can be found here: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments
  b <N>: sets the memory size to 2<sup>N</sup> entries
  q <ab>: create quadratic feature interactions between features in namespaces starting with 'a' and 'b'
"""
model = VW(col_user="userID", col_item="itemID", col_rating="rating", b=26, q="ui")

with Timer() as train_time:
    model.fit(train)

with Timer() as test_time:
    predictions = model.predict(test)

result = evaluate(test, predictions, train_time.interval, test_time.interval)

# keep this model and its results for the top-k recommendations below
saved_model = model
saved_result = result

comparison = pd.concat([comparison, pd.DataFrame(result, index=['Linear Regression w/ Interaction'])])
comparison

,RMSE,MAE,R2,Explained Variance,Train Time (ms),Test Time (ms)
Linear Regression,0.988453,0.70992,0.227245,0.227255,225.956585,326.466013
Linear Regression w/ Interaction,0.985921,0.71292,0.231199,0.231338,789.101393,172.026851

## 2.3 Multinomial Logistic Regression

An alternative to linear regression is to leverage multinomial logistic regression, or multiclass classification, which treats each rating value as a distinct class. 

This avoids any non integer results, but also reduces the training data for each class which could lead to poorer performance if the counts of different rating levels are skewed.

Basic multiclass logistic regression can be accomplished using the One Against All approach specified by the '--oaa N' option, where N is the number of classes and proving the logistic option for the loss function to be used.

In [7]:
"""
Quick description of the parameters used, these are the vw command line options passed as keyword arguments
  Other optional parameters can be found here: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments
  loss_function logistic: sets the model loss function for logistic regression
  oaa <N>: trains N separate models using One-Against-All approach (all models are captured in the single model file)
           This expects the labels to be contiguous integers starting at 1
  link logistic: converts the predicted output from logit to probability, this option is only used at prediction time
The predicted output is the model (label) with the largest likelihood
"""
model = VW(col_user="userID", col_item="itemID", col_rating="rating", loss_function="logistic", oaa=5, link="logistic")

with Timer() as train_time:
    model.fit(train)

with Timer() as test_time:
    predictions = model.predict(test)

result = evaluate(test, predictions, train_time.interval, test_time.interval)

comparison = pd.concat([comparison, pd.DataFrame(result, index=['Multinomial Regression'])])
comparison

,RMSE,MAE,R2,Explained Variance,Train Time (ms),Test Time (ms)
Linear Regression,0.988453,0.70992,0.227245,0.227255,225.956585,326.466013
Linear Regression w/ Interaction,0.985921,0.71292,0.231199,0.231338,789.101393,172.026851
Multinomial Regression,2.770119,2.53164,-5.069131,0.000000,374.639162,142.829157

## 2.4 Logistic Regression

Additionally, one might simply be interested in whether the user likes or dislikes an item and we can adjust the input data to represent a binary outcome, where ratings in (1,3] are dislikes (negative results) and (3,5] are likes (positive results).

This framing allows for a simple logistic regression model to be applied. To perform logistic regression the loss_function parameter is changed to 'logistic' and the target label is switched to [0, 1]. Also, be sure to set '--link logistic' during prediction to convert the logit output back to a probability value.

In [8]:
"""
Quick description of the parameters used, these are the vw command line options passed as keyword arguments
  Other optional parameters can be found here: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments
  loss_function logistic: sets the model loss function for logistic regression, the class also converts the training ratings to a binary label
  link logistic: converts the predicted output from logit to probability, this option is only used at prediction time
"""
model = VW(col_user="userID", col_item="itemID", col_rating="rating", loss_function="logistic", link="logistic")

with Timer() as train_time:
    model.fit(train)

with Timer() as test_time:
    predictions = model.predict(test)

result = evaluate(test, predictions, train_time.interval, test_time.interval, logistic=True)

comparison = pd.concat([comparison, pd.DataFrame(result, index=['Logistic Regression'])])
comparison

,RMSE,MAE,R2,Explained Variance,Train Time (ms),Test Time (ms)
Linear Regression,0.988453,0.709920,0.227245,0.227255,225.956585,326.466013
Linear Regression w/ Interaction,0.985921,0.712920,0.231199,0.231338,789.101393,172.026851
Multinomial Regression,2.770119,2.531640,-5.069131,0.000000,374.639162,142.829157
Logistic Regression,0.717475,0.409551,0.096363,0.142501,281.469503,149.084709

# 3. Matrix Factorization Based Recommendations

All of the above approaches train a regression model, but VW also supports matrix factorization with two different approaches.

As opposed to learning direct weights for specific users, items and interactions when training a regression model, matrix factorization attempts to learn latent factors that determine how a user rates an item. An example of how this might work is if you could represent user preference and item categorization by genre. Given a smaller set of genres we can associate how much each item belongs to each genre class, and we can set weights for a user's preference for each genre. Both sets of weights could be represented as a vectors where the inner product would be the user-item rating. Matrix factorization approaches learn low rank matrices for latent features of users and items such that those matrices can be combined to approximate the original user item matrix.

## 3.1. Singular Value Decomposition Based Matrix Factorization

The first approach performs matrix factorization based on Singular Value Decomposition (SVD) to learn a low rank approximation for the user-item rating matix. It is is called using the '--rank' command line argument.

See the [Matrix Factorization Example](https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Matrix-factorization-example) for more detail.

In [9]:
"""
Quick description of the parameters used, these are the vw command line options passed as keyword arguments
  Other optional parameters can be found here: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments
  rank <N>: sets the number of latent factors in the reduced matrix
"""
model = VW(col_user="userID", col_item="itemID", col_rating="rating", rank=5, q="ui")

with Timer() as train_time:
    model.fit(train)

with Timer() as test_time:
    predictions = model.predict(test)

result = evaluate(test, predictions, train_time.interval, test_time.interval)

comparison = pd.concat([comparison, pd.DataFrame(result, index=['Matrix Factorization (Rank)'])])
comparison

,RMSE,MAE,R2,Explained Variance,Train Time (ms),Test Time (ms)
Linear Regression,0.988453,0.709920,0.227245,0.227255,225.956585,326.466013
Linear Regression w/ Interaction,0.985921,0.712920,0.231199,0.231338,789.101393,172.026851
Multinomial Regression,2.770119,2.531640,-5.069131,0.000000,374.639162,142.829157
Logistic Regression,0.717475,0.409551,0.096363,0.142501,281.469503,149.084709
Matrix Factorization (Rank),1.010723,0.745800,0.192033,0.221080,573.389722,420.375986

## 3.2. Factorization Machine Based Matrix Factorization

An alternative approach based on [Rendel's factorization machines](https://cseweb.ucsd.edu/classes/fa17/cse291-b/reading/Rendle2010FM.pdf) is called using '--lrq' (low rank quadratic). More LRQ details in this [demo](https://github.com/VowpalWabbit/vowpal_wabbit/tree/master/demo/movielens).

This learns two lower rank matrices which are multiplied to generate an approximation of the user-item rating matrix. Compressing the matrix in this way leads to learning generalizable factors which avoids some of the limitations of using regression models with extremely sparse interaction features. This can lead to better convergence and smaller on-disk models.

An additional term to improve performance is --lrqdropout which will dropout columns during training. This however tends to increase the optimal rank size. Other parameters such as L2 regularization can help avoid overfitting.

In [10]:
"""
Quick description of the parameters used, these are the vw command line options passed as keyword arguments
  Other optional parameters can be found here: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Command-Line-Arguments
  lrq <abN>: learns approximations of rank N for the quadratic interaction between namespaces starting with 'a' and 'b'
  lrqdropout: performs dropout during training to improve generalization
"""
model = VW(col_user="userID", col_item="itemID", col_rating="rating", lrq="ui7")

with Timer() as train_time:
    model.fit(train)

with Timer() as test_time:
    predictions = model.predict(test)

result = evaluate(test, predictions, train_time.interval, test_time.interval)

comparison = pd.concat([comparison, pd.DataFrame(result, index=['Matrix Factorization (LRQ)'])])
comparison

,RMSE,MAE,R2,Explained Variance,Train Time (ms),Test Time (ms)
Linear Regression,0.988453,0.709920,0.227245,0.227255,225.956585,326.466013
Linear Regression w/ Interaction,0.985921,0.712920,0.231199,0.231338,789.101393,172.026851
Multinomial Regression,2.770119,2.531640,-5.069131,0.000000,374.639162,142.829157
Logistic Regression,0.717475,0.409551,0.096363,0.142501,281.469503,149.084709
Matrix Factorization (Rank),1.010723,0.745800,0.192033,0.221080,573.389722,420.375986
Matrix Factorization (LRQ),1.015145,0.726920,0.184947,0.184951,321.737970,187.180061

# 4. Conclusion

The table above shows a few of the approaches in the VW library that can be used for recommendation prediction. The relative performance can change when applied to different datasets and properly tuned, but it is useful to note the rapid speed at which all approaches are able to train (75,000 examples) and test (25,000 examples).

# 5. Scoring

After training a model with any of the above approaches, the model can be used to score potential user-pairs in offline batch mode, or in a real-time scoring mode. The example below uses the linear regression model with interaction features saved above to score, for every user in the test set, all the items seen during training that the user has not rated yet, and keeps the top K items per user.

In [11]:
# score all unseen items for each user with the saved model and keep the top k
with Timer() as test_time:
    top_k = saved_model.recommend_k_items(test, top_k=TOP_K, remove_seen=True)

top_k.head()

   userID  itemID  prediction
0       1     318    4.565878
1       1      64    4.533299
2       1     408    4.530735
3       1     603    4.525893
4       1     483    4.501389

In [12]:
# get ranking metrics
args = [test, top_k]
kwargs = dict(col_user='userID', col_item='itemID', col_rating='rating', col_prediction='prediction',
              relevancy_method='top_k', k=TOP_K)

rank_metrics = {'MAP': map_at_k(*args, **kwargs), 
                'NDCG': ndcg_at_k(*args, **kwargs),
                'Precision': precision_at_k(*args, **kwargs),
                'Recall': recall_at_k(*args, **kwargs)}

In [13]:
# final results
all_results = ['{k}: {v}'.format(k=k, v=v) for k, v in saved_result.items()]
all_results += ['{k}: {v}'.format(k=k, v=v) for k, v in rank_metrics.items()]
print('\n'.join(all_results))

RMSE: 0.9859208893212478
MAE: 0.71292
R2: 0.23119931215379363
Explained Variance: 0.2313379575958101
Train Time (ms): 789.1013930002373
Test Time (ms): 172.02685099982773
MAP: 0.041644809541729715
NDCG: 0.09672023122829305
Precision: 0.09766454352441616
Recall: 0.037680076229949976

In [14]:
# Record results for tests - ignore this cell
store_metadata('rmse', saved_result['RMSE'])
store_metadata('mae', saved_result['MAE'])
store_metadata('rsquared', saved_result['R2'])
store_metadata('exp_var', saved_result['Explained Variance'])
store_metadata("train_time", saved_result['Train Time (ms)'])
store_metadata("test_time", test_time.interval)
store_metadata('map', rank_metrics['MAP'])
store_metadata('ndcg', rank_metrics['NDCG'])
store_metadata('precision', rank_metrics['Precision'])
store_metadata('recall', rank_metrics['Recall'])

## References

1. John Langford, et. al. Vowpal Wabbit Wiki. URL: https://github.com/VowpalWabbit/vowpal_wabbit/wiki
2. Steffen Rendel. Factorization Machines. 2010 IEEE International Conference on Data Mining.
3. Jake Hoffman. Matrix Factorization Example. URL: https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Matrix-factorization-example
4. Paul Minero. Low Rank Quadratic Example. URL: https://github.com/VowpalWabbit/vowpal_wabbit/tree/master/demo/movielens